'use strict'

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Pairs',
      [
        {
          ape_id: 3,
          farther_id: 1,
          mother_id: 2,
          partner_id: 4,
          in_law: false,
        },
        {
          ape_id: 4,
          farther_id: 1,
          mother_id: 2,
          partner_id: 3,
          in_law: true,
        },
        {
          ape_id: 5,
          farther_id: 1,
          mother_id: 2,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 6,
          farther_id: 1,
          mother_id: 2,
          partner_id: 7,
          in_law: false,
        },
        {
          ape_id: 7,
          farther_id: 1,
          mother_id: 2,
          partner_id: 6,
          in_law: true,
        },
        {
          ape_id: 8,
          farther_id: 1,
          mother_id: 2,
          partner_id: 9,
          in_law: false,
        },
        {
          ape_id: 9,
          farther_id: 1,
          mother_id: 2,
          partner_id: 8,
          in_law: true,
        },
        {
          ape_id: 10,
          farther_id: 1,
          mother_id: 2,
          partner_id: 11,
          in_law: false,
        },
        {
          ape_id: 11,
          farther_id: 1,
          mother_id: 2,
          partner_id: 10,
          in_law: true,
        },
        {
          ape_id: 12,
          farther_id: 3,
          mother_id: 4,
          partner_id: 13,
          in_law: false,
        },
        {
          ape_id: 13,
          farther_id: 3,
          mother_id: 4,
          partner_id: 12,
          in_law: true,
        },
        {
          ape_id: 14,
          farther_id: 3,
          mother_id: 4,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 15,
          farther_id: 3,
          mother_id: 4,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 16,
          farther_id: 6,
          mother_id: 7,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 17,
          farther_id: 6,
          mother_id: 7,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 18,
          farther_id: 8,
          mother_id: 9,
          partner_id: 19,
          in_law: true,
        },
        {
          ape_id: 19,
          farther_id: 8,
          mother_id: 9,
          partner_id: 18,
          in_law: false,
        },
        {
          ape_id: 20,
          farther_id: 8,
          mother_id: 9,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 21,
          farther_id: 10,
          mother_id: 11,
          partner_id: 22,
          in_law: true,
        },
        {
          ape_id: 22,
          farther_id: 10,
          mother_id: 11,
          partner_id: 21,
          in_law: false,
        },
        {
          ape_id: 23,
          farther_id: 10,
          mother_id: 11,
          partner_id: 24,
          in_law: true,
        },
        {
          ape_id: 24,
          farther_id: 10,
          mother_id: 11,
          partner_id: 23,
          in_law: false,
        },
        {
          ape_id: 25,
          farther_id: 10,
          mother_id: 11,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 26,
          farther_id: 13,
          mother_id: 12,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 27,
          farther_id: 18,
          mother_id: 19,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 28,
          farther_id: 18,
          mother_id: 19,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 29,
          farther_id: 22,
          mother_id: 21,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 30,
          farther_id: 24,
          mother_id: 23,
          partner_id: null,
          in_law: false,
        },
        {
          ape_id: 31,
          farther_id: 24,
          mother_id: 23,
          partner_id: null,
          in_law: false,
        },
      ],
      {}
    )
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Pairs', null, {})
  },
}
